name: math-api CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }} environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm install yarn
          yarn install
      - name: Run tests
        run: yarn run test

